// <auto-generated />
using Escarolin_P1_AP1.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Escarolin_P1_AP1.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20201005233704_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8");

            modelBuilder.Entity("Escarolin_P1_AP1.Entidades.Cuidades", b =>
                {
                    b.Property<int>("CuidadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombres")
                        .HasColumnType("TEXT");

                    b.HasKey("CuidadId");

                    b.ToTable("Cuidades");
                });
#pragma warning restore 612, 618
        }
    }
}
